name: Deploy React App to Ubuntu VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VM using SSH and password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          sudo apt update
          sudo apt install -y nodejs npm nginx

          sudo systemctl enable nginx
          sudo systemctl start nginx

          rm -rf ~/my-react-app
          git clone https://github.com/${{ github.repository }}.git ~/my-react-app
          cd ~/my-react-app

          npm install
          npm run build

          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html

          echo 'server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.html;

              location / {
                  try_files $uri /index.html;
              }

              error_page 404 /index.html;
          }' | sudo tee /etc/nginx/sites-available/default > /dev/null

          sudo systemctl restart nginx
